apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qc0056k5a-python 
  janus-idp.io/tekton: qc0056k5a-python
  backstage.io/kubernetes-id: qc0056k5a-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qc0056k5a-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml